// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2gVu4BBdjxQhvfo2Q-igsBhgcdFWx5mg',
    appId: '1:493582876285:web:1ff3999311f03d8289bb14',
    messagingSenderId: '493582876285',
    projectId: 'thriftthem-3b760',
    authDomain: 'thriftthem-3b760.firebaseapp.com',
    storageBucket: 'thriftthem-3b760.firebasestorage.app',
    measurementId: 'G-0TH9MEJ3Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGu7denvq3PukpAhfvqHFuzbp37mlnd6w',
    appId: '1:493582876285:android:060c02de8b1773bd89bb14',
    messagingSenderId: '493582876285',
    projectId: 'thriftthem-3b760',
    storageBucket: 'thriftthem-3b760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4q7UydG44osEN6CUv7_Uwr2JRJpw9C5M',
    appId: '1:493582876285:ios:ae017daa4595683889bb14',
    messagingSenderId: '493582876285',
    projectId: 'thriftthem-3b760',
    storageBucket: 'thriftthem-3b760.firebasestorage.app',
    iosBundleId: 'com.example.thriftthem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4q7UydG44osEN6CUv7_Uwr2JRJpw9C5M',
    appId: '1:493582876285:ios:ae017daa4595683889bb14',
    messagingSenderId: '493582876285',
    projectId: 'thriftthem-3b760',
    storageBucket: 'thriftthem-3b760.firebasestorage.app',
    iosBundleId: 'com.example.thriftthem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2gVu4BBdjxQhvfo2Q-igsBhgcdFWx5mg',
    appId: '1:493582876285:web:c446b1f2f205c9f889bb14',
    messagingSenderId: '493582876285',
    projectId: 'thriftthem-3b760',
    authDomain: 'thriftthem-3b760.firebaseapp.com',
    storageBucket: 'thriftthem-3b760.firebasestorage.app',
    measurementId: 'G-FD1WVRY2MB',
  );
}
